% Prints all the male ancestors of Jesus Christ

father(abraham,isaac).
father(isaac,jacob1).
father(jacob1,judah).
father(judah,perez).
father(judah,zerah).
father(perez,hezron).
father(hezron,ram).
father(ram,amminadab).
father(amminadab,nahshon).
father(nahshon,salmon).
father(salmon,boaz).
father(boaz,obed).
father(obed,jesse).
father(jesse,david).
father(david,solomon).
father(solomon,rehoboam).
father(rehoboam,abijah).
father(abijah,asa).
father(asa,jehoshaphat).
father(jehoshaphat,jehoram).
father(jehoram,uzziah).
father(uzziah,jotham).
father(jotham,ahaz).
father(ahaz,hezekiah).
father(hezekiah,manasseh).
father(manasseh,amon).
father(amon,josiah).
father(josiah,jeconiah).
father(jeconiah,shealtiel).
father(shealtiel,zerubbabel).
father(zerubbabel,abihud).
father(abihud,eliakim).
father(eliakim,azor).
father(azor,zadok).
father(zadok,akim).
father(akim,elihud).
father(elihud,eleazar).
father(eleazar,matthan).
father(matthan,jacob2).
father(jacob2,joseph).
father(joseph,jesus).

ancestor(X,Y):-father(X,Y).
ancestor(Z,Y):-father(X,Y),ancestor(Z,X).
